services:
  mongodb:
    build: ./MongoDb_Debian
    volumes:
      - ./MongoDb_Debian/data/db:/data/db
    hostname: mongodb
    ports:
      - "27017:27017"
    expose: 
      - 27017
    container_name: MongoDB
    networks: 
      notes-network:
        ipv4_address: 172.29.1.1
  
  express:
    build: ./Notes_Express
    ports:
      - "3000:3000"
    environment: 
      - MONGOOSE_ADDRESS=mongodb://mongodb:27017/notes
      - PORT=3000
      - CORSHEADER=http://172.29.1.3:5000
    hostname: express
    expose: 
      - 3000
    container_name: Express
    networks: 
      notes-network:
        ipv4_address: 172.29.1.2
    depends_on:
      - "mongodb"
    
  react:
    build: ./Notes_React
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000
    container_name: React
    networks: 
      notes-network:
        ipv4_address: 172.29.1.3
    depends_on:
      - "express"


networks:
  notes-network:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16